apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: classified

spec:
  replicas: 3

  selector:
    matchLabels:
      app: backend


  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: divar-backend:1.0.3
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: backend-config

          livenessProbe:
            httpGet:
              path: /health/live/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health/ready/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
