apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: classified

spec:
  replicas: 3

  selector:
    matchLabels:
      app: backend


  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: divar-backend:1.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef: 
                name: backend-config
